Repository Emplea-do/MobileApp-ReactNative, pull requests merged in 2019-11, with the labels that each got.

#13 Pull Request template added to repository
  .github/pull_request_template.md
Labels: enhancement

#14 App Shell (Merge to master)
  android/app/build.gradle
  package.json
  src/App.js
  src/constants/screens.js
  src/navigation/index.js
  src/navigation/profile.stack.js
  src/navigation/search.stack.js
  src/navigation/settings.stack.js
  src/screens/Profile.js
  src/screens/Search.js
  src/screens/Settings.js
  src/theme/colors.js
  src/theme/index.js
Labels: need code review

#11 Agregando repositorio de servicio para empleo
  babel.config.js
  example.env
  index.js
  package.json
  src/constants/services.js
  src/services/job.js
Labels: need code review

#18 Agregado documentacion sobre variables de entorno
  README.md
Labels: documentation, need code review

#16 Se agregó Husky
  .huskyrc.json
  .lintstagedrc.json
  package-lock.json
  package.json
Labels: working in progress

#15 Creación de instancia Axios
  src/App.js
  src/constants/index.js
  src/constants/screens.js
  src/constants/services.js
  src/navigation/index.js
  src/services/index.js
  src/services/job.js
  src/utils/api.js
  src/utils/index.js
Labels: need code review

#19 Se agregó el default theme
  src/navigation/index.js
  src/navigation/profile.stack.js
  src/navigation/search.stack.js
  src/navigation/settings.stack.js
  src/theme/colors.js
  src/theme/index.js
Labels: need code review

#26 Se agrego script appcenter para procesar env vars
  appcenter-pre-build.sh
Labels: need code review
